### ISSUE TITLE
Concept challenge: Checklist

### ISSUE THREAD

**Issue by vic-topcoder** [topcoder-platform/Design-Pool#1]
Launch a new concept challenge that will increase engagement through interactive task list for users. The goal is to design a platform solution that displays a list of tasks to be completed to the users. The tasks might be sequential or non-sequential, required and optional, and they should be visible at particular centralized UI interfaces. Explore all flows (complete profile, select interests, read an article, sign a document, create work requirement, etc.) and placements (dashboard, sidebar, challenge card, work card, etc.).

**Comment by vic-topcoder** [comment]
Let's run with:

- Mandatory checklist - you have to finish all steps, in order
- Optional checklist - you can finish any step at any time

- Checklist in sidebar
- Checklist on dashboard
- Checklist on a connect card
- Checklist on a challenge

**Comment by vic-topcoder** [comment]
Users - we want to design for novice community member, and connect customer. The goal is to guide them through the system.

**Comment by vic-topcoder** [comment]
We're looking for something like the LinkedIn profile strength widget:
![2927399489_5a458fa5d4_o](https://user-images.githubusercontent.com/8484061/57395393-dda56c00-717c-11e9-831f-7e81d8ad4cc6.png)

**Comment by iaminfinite** [comment]
It has been launched as a challenge, right? @vic-topcoder @Dara-K

**Comment by Dara-K** [comment]
@iaminfinite Yes, it's the challenge you registered for: https://www.topcoder.com/challenges/30090505?tab=details
